version: "2"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ".:/code"
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0.3
    ports:
      - "27017:27017"
    command: mongod